### ISSUE TITLE
What are the advantages of this textobject vs ciw?

### ISSUE THREAD

**Issue by kiryph** [saihoooooooo/vim-textobj-space#1]
I do not understand what this text object can do what you cannot do with `iw`. Could you provide an example in your README.md?

**Comment by saihoooooooo** [comment]
I tried it now. It looks good with `iw`.
I do not know why I made this. I thought that it was necessary at that time...
So use `iw`. I also use it.
Thank you.

**Comment by kiryph** [comment]
I see. Thanks for your thoughts. Maybe some people prefer to have dedicated objects for sementically different things. However, a simple alias would be sufficient.
